# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/main-*.dart"
    - "lib/flavors.dart"

  errors:
    avoid_classes_with_only_static_members: ignore
    invalid_annotation_target: ignore